### ISSUE TITLE
Attention Map 

### ISSUE THREAD

**Issue by liuaishan** [shaneopatrick/lzbdr#1]
Hi, Shane!

Good to see your repo here! It's real cool!
I am really interested in the attention map generation process. So, did you use any insights from the paper 'Diversified Visual Attention Networks for Fine-Grained Object Classification'? And how could I run your python code?

Best

**Comment by shaneopatrick** [comment]
Hi liuaishan, thanks for checking out my repo! Yes I was very interested in creating an attention map and tried to implement my own version in Lasagne based on then paper you mentioned. Unfortunately I was unsuccessful and my current solution does not utilize an attention map. 

However I have a friend who was able to implement one using Keras, which offers a time distributed wrapper - the component needed for using a LSTM-CNN network. You had find his repo here: https://github.com/shomerj/Video-Classification.

**Comment by liuaishan** [comment]
Hi Shane!
Appreciate for your reply!
Your suggestions and repo you gave were really helpful.
Thanks!

Best,
Aishan Liu

**Comment by shaneopatrick** [comment]
Happy to help!
